"""add_foreign_keys_and_constraints

Revision ID: 9df4f9e4eab4
Revises: b902d9d86fb5
Create Date: 2026-01-12 15:26:19.207205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9df4f9e4eab4'
down_revision: Union[str, Sequence[str], None] = 'b902d9d86fb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'learning_audio_lessons', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'learning_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'learning_transcripts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'vocabulary_cards', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vocabulary_cards', type_='foreignkey')
    op.drop_constraint(None, 'learning_transcripts', type_='foreignkey')
    op.drop_constraint(None, 'learning_sessions', type_='foreignkey')
    op.drop_constraint(None, 'learning_audio_lessons', type_='foreignkey')
    # ### end Alembic commands ###
