"""learning initial schema

Revision ID: b902d9d86fb5
Revises: 
Create Date: 2025-12-27 18:10:16.090495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b902d9d86fb5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_audio_lessons',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=False),
    sa.Column('segments', sa.JSON(), nullable=False),
    sa.Column('audio_filename', sa.String(), nullable=False),
    sa.Column('audio_mime_type', sa.String(length=120), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_learning_audio_lessons_user_lang', 'learning_audio_lessons', ['user_id', 'language'], unique=False)
    op.create_table('learning_sessions',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_learning_sessions_user_lang', 'learning_sessions', ['user_id', 'language'], unique=False)
    op.create_table('learning_transcripts',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('lesson_audio_folder_id', sa.String(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('notes', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_learning_transcripts_user_lang', 'learning_transcripts', ['user_id', 'language'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('vocabulary_cards',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('word', sa.String(length=100), nullable=False),
    sa.Column('translation', sa.Text(), nullable=True),
    sa.Column('notes', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('interval_days', sa.Integer(), nullable=False),
    sa.Column('ease', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('lapses', sa.Integer(), nullable=False),
    sa.Column('streak_correct', sa.Integer(), nullable=False),
    sa.Column('last_grade', sa.String(length=8), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vocab_due_queue', 'vocabulary_cards', ['user_id', 'language', 'status', 'due_at'], unique=False)
    op.create_index('ix_vocabulary_cards_user_lang', 'vocabulary_cards', ['user_id', 'language'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vocabulary_cards_user_lang', table_name='vocabulary_cards')
    op.drop_index('ix_vocab_due_queue', table_name='vocabulary_cards')
    op.drop_table('vocabulary_cards')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_learning_transcripts_user_lang', table_name='learning_transcripts')
    op.drop_table('learning_transcripts')
    op.drop_index('ix_learning_sessions_user_lang', table_name='learning_sessions')
    op.drop_table('learning_sessions')
    op.drop_index('ix_learning_audio_lessons_user_lang', table_name='learning_audio_lessons')
    op.drop_table('learning_audio_lessons')
    # ### end Alembic commands ###
